### local test
POST http://localhost:7071/api/getTheme

{
  "Title": "Computing"
}

### get status
GET http://localhost:7071/api/getTheme/status/0c4d99162afa47a9ad5c518a4bb30440

### get sub themes
POST http://localhost:7071/api/getSubThemes

{
  "Title": "Geography"
}

### deployed
POST https://top-func.azurewebsites.net/api/getTheme

{
  "Title": "Computing"
}

### get status
GET https://top-func.azurewebsites.net/api/getTheme/status/129c8668983d4f988153f29fafb197b1

### get sub themes
POST https://top-func.azurewebsites.net/api/getSubThemes

{
  "Title": "Geography"
}